### PR TITLE
WIP: Apache pieces

### PR DESCRIPTION
**Pull request by stephhazlitt**
This PR is an attempt to address items listed in Issue #25. 

I suggest code reviews by @JustinCally @ateucher and @boshek before merge consideration. 

Current state is an attempt to bring in the {bcdata} source code Apache 2.0 licence elements with modifications still licensed under MIT. A simplification would be to switch the modifications to the Apache 2.0 licence (tasks would be: rm LICENCE.md file, rename LICENCE-APACHE2.md -> LICENCE.md, rm MIT in footer of README, rm MIT from `DESCRIPTION` file).

### CODE REVIEW

**Comment by stephhazlitt** [comment]
@JustinCally One Apache 2.0 piece I did not tackle is the description of changes in the relevant `.R` files.

**Comment by JustinCally** [comment]
Thanks @stephhazlitt. I made some modifications to get through the checks and have removed my original MIT licence so that both myself and  the Province of British Columbia are copyright holders. As Andy said, this is probably easier. I'll add the state changes for the R and test files over the next couple of days.

**Comment by ateucher** [comment]
This is looking great @stephhazlitt and @JustinCally - thanks!

**Comment by boshek** [comment]
Looks good to me. Thanks to @stephhazlitt for doing the heavy lifting here.

**Comment by JustinCally** [comment]
Thanks @stephhazlitt @ateucher @boshek 

If you are all happy I will accept the pull request and make a CRAN release

**Pull request merged**
